Seperated Acess Control in to a abtract class
masslbs/contracts pull request #17
Opened 2024-03-14 09:25 UTC by wanderer

This separates the access control into a class. The AccessControl class has a map that assoiciates each user to a bitmap of permissions. 

I used a enum in the base class and RelayReg to store the varous permissions.  Unfortiantly we cannot shadow or override enums from the base class so we need to use two different enums and we have to use uint8's in the functions signatures instead of a shared enum. I have not found a better way to do this yet.

2024-03-14 09:56 UTC, cryptix requested changes
Nothing major. A few naming questions and typos but I do like the separation of concerns.

2024-03-14 09:56 UTC, cryptix commented on src/StoreReg.sol
>  /// @notice Owner only usable for hasAtLeastAccess checking
move these down to the new constants

2024-03-14 09:56 UTC, cryptix commented on src/StoreReg.sol
> +        (1 << uint8(Permissions.publishInviteVerifier));
Since this is a bit more granular then before, how about changing these to terms about what one is able _to do_? That fits better to what Roles are, as in, it's not a group of people per se.

_Admin_ and _Relay Admin_ might be a bit confusing (which is the superset of which?) for a similar reason.

How about:

* Clerk => Inventory (Management)
* Relay Admin => Relay/Replication (Management)
* Admin => Staffing

2024-03-14 09:56 UTC, cryptix commented on src/AccessControl.sol
> +    function hasAllorMorePermissions(uint256 id, address user, uint256 perms) public view returns (bool) {
```suggestion
    function hasEnoughPermissions(uint256 id, address user, uint256 perms) public view returns (bool) {
```

2024-03-14 09:56 UTC, cryptix commented on src/AccessControl.sol
> +abstract contract AccessControl is ERC721 {
guessing from C++, i would have assumed an 'abstract' thing expects a function to be implemented by the contract inheriting this but AFAICT all functions are implemented here?

2024-03-14 09:56 UTC, cryptix commented on src/AccessControl.sol
> +    function hasAllorMorePermissions(uint256 id, address user, uint256 perms) public view returns (bool) {
or capitalize the Or to make it more readable

2024-03-14 09:56 UTC, cryptix commented on src/StoreReg.sol
> +    }
the granularity here makes me a bit uneasy if we don't really use it to assign permissions on this level anyway but i could be overlooking something.

2024-03-14 09:56 UTC, cryptix commented on test/store-users.t.sol
>  contract StoreUsersTest is Test {
maybe we should gut this and make it specifically about the new contract?

2024-03-14 10:45 UTC, wanderer commented on src/AccessControl.sol
> +abstract contract AccessControl is ERC721 {
Yes, it is a C++ thing. We don't have any virtual functions, so abstract here just mean you cannot create this Contract directly. It must be inherited.

2024-03-14 11:41 UTC, wanderer commented on src/StoreReg.sol
> +    }
The owner of the store has access to assigning them vai `Add/RemovePermission` in AccessControl.sol so they are exposed.  But I will simplefly it for now.

2024-03-14 11:43 UTC, wanderer commented on test/store-users.t.sol
>  contract StoreUsersTest is Test {
i agree, will do

2024-03-15 17:51 UTC, wanderer commented on src/StoreReg.sol
> +    }
I removed explicit roles. Roles can still be defined, just externally.

2024-03-15 17:56 UTC, wanderer commented on test/store-users.t.sol
>  contract StoreUsersTest is Test {
ended keeping this for now, since it is like an integration test

2024-05-28 05:30 UTC, cryptix commented
Re-opening with different branch name for CI testing.

2024-05-28 05:30 UTC, closed without merging